server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka #config-server
          uri: https://github.com/jespinoza0388/microservicio-curso
          search-paths: config-data
  application:
    name: config-service